### ISSUE TITLE
issue with connecting

### ISSUE THREAD

**Issue by jonasrhee1208wastaken** [cloudlink-omega/extension#1]
even with default ugi, the connect dosen't seem to work. maybe try using webshell instead of websecureshell? cloudlink 4 uses webshell and it works, but this uses websecureshell and dosen't work.

**Comment by MikeDev101** [comment]
What? CloudLink 4 uses WebSockets, not a webshell. 

If you're trying to use the extension(s) in an insecure context (http://) it will not work. 
CL5 uses WebRTC, which a secure context (https://) is *mandatory*. The API blocks will provide logging information in your browser's inspect console, maybe you can provide me with an output of that?

Also, if you're trying to test the extensions on your own, you need *two* sessions with *two* different accounts to test things out. RTFM.
