### ISSUE TITLE
Is There a Way to Delete an CLΩ Account?

### ISSUE THREAD

**Issue by hammouda101010** [cloudlink-omega/extension#3]
I Just Made A Sign-in and Log-in feature, but i wish i could just delete my accounts to make another ones. is there a way to do it?

**Comment by MikeDev101** [comment]
Not via the API at this time. It is a manual process. Which username should
I use to delete the account?

**Comment by hammouda101010** [comment]
hammouda101010

**Comment by hammouda101010** [comment]
it would be nice to do it on the API instead of doing it manually.

**Comment by MikeDev101** [comment]
> it would be nice to do it on the API instead of doing it manually.

I haven't got the chance to implement much needed functionality yet. Just had my car get sent in for repairs. It's been a fun week.

**Comment by hammouda101010** [comment]
@MikeDev101 i hope it gets fixed by now. BTW did you delete the account?

**Comment by MikeDev101** [comment]
Just did.

**Comment by hammouda101010** [comment]
@MikeDev101 TYSM! 😀😀😀
