### ISSUE TITLE
How to use your own UGI without the default one?

### ISSUE THREAD

**Issue by hammouda101010** [cloudlink-omega/extension#4]
i would ike to use my own unique UGI, but doing it wo0nt make the servers work. is there any way to do it? or is it manual?

**Comment by MikeDev101** [comment]
There is a registration process for obtaining a UGI (Unique Game Identifier) that is currently a manual process, which is handled via our Discord server https://discord.gg/BZ7TWeMF75 .

In the future there will be a feature via the extension to generate a temporary UGI for development. But this requires features in the backend that are currently on my to do list.

For the meantime, if you want to use any UGI for development, your only option is to spin up an Omega server in Authless mode: https://github.com/cloudlink-omega/backend

**Comment by hammouda101010** [comment]
@MikeDev101 sorry i don't want to use discord for this registration process, is there another way to do this?

**Comment by MikeDev101** [comment]
> @MikeDev101 sorry i don't want to use discord for this registration process, is there another way to do this? and how do you even spin up an omega server in Authless mode?

Sorry for the late reply. See the following attached guide on how to spin up an Authless mode server (cc'd from the discord server):

# How to run your own server

## Requirements
* A copy of Go on your computer/server - Follow https://go.dev/doc/install
* (*Optional*) A SQL database server

## Downloading a copy

### For the lazy
1. Go to https://github.com/cloudlink-omega/backend
2. Click on "Code".
3. Click on "Download ZIP".
4. Extract the newly downloaded zip file.
5. Go to wherever the extracted files are.

### For the savvy
1. `git clone https://github.com/cloudlink-omega/backend`
2. `cd backend`

## Building a binary
Run `go mod tidy` to collect/update dependencies needed to make the server work, then run `go build .` to generate an executable binary.

## Running your binary
Depending on if you run a Windows/*Nix machine, either run `backend.exe` or `./backend`.

## Configuring your server
Make a copy of `.env.example` and rename it to `.env`. 

* `AUTHLESS_MODE` - Default to `false`. If `true`, this will run the server without any SQL DB needing to be present. *There is no storage/auth support with this mode on, and has absolutely zero security whatsoever.*
* `USE_IN_MEMORY_CLIENT_MGR` - **Leave set to `true` for now.**
* `DB_HOST` - File path (SQLite file) or IP address & port (DB server) to your database.
* `DB_USER` - Database server user (ignore if SQLite)
* `DB_PASS` - Database server password (ignore if SQLite)
* `DATABASE` - Select which DB collection will store CloudLink Omega. Leave set to `clomega`.
* `API_HOST` - Specifies which interface to listen to requests. Use `127.0.0.1` for local testing, or use `0.0.0.0` to test on your local network/expose to the internet (please don't do this without a reverse proxy).
* `API_PORT` - Specifies which port to listen to requests. Defaults to `3000`.

## Exposing it to the interwebs
See https://github.com/MikeDev101/cloudlink/discussions/56 for supported services.
